# Generated by Django 3.0.2 on 2020-02-19 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pythonclubapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productType',
            new_name='TechType',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name_plural': 'reviews'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='producturl',
            new_name='productURL',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='producttype',
            new_name='techtype',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='reviewrating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='techtype',
            old_name='productdescription',
            new_name='techdescription',
        ),
        migrations.RenameField(
            model_name='techtype',
            old_name='typename',
            new_name='techtypename',
        ),
        migrations.AddField(
            model_name='product',
            name='productprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='productdescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pythonclubapp.Product'),
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='review',
            table='review',
        ),
    ]
