# Generated by Django 3.0.2 on 2020-02-21 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pythonclubapp', '0003_auto_20200219_1937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pythonclubapp.Product'),
        ),
        migrations.AlterField(
            model_name='techtype',
            name='techdescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
