# Generated by Django 3.0.2 on 2020-02-21 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pythonclubapp', '0005_auto_20200220_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pythonclubapp.Product'),
        ),
    ]
